import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>TESTE</h1>
        <button className="bg-pink-500 hover:bg-pink-700 text-white font-bold py-2 px-4 rounded-full">
          Button
        </button>
      </main>
    </div>
  )
}
